APP_ENV: ENC[AES256_GCM,data:k/TXHTCpv6xatw==,iv:CnJFJC3ZaxojJgzcVR7tbBEWK+XNmqyeT5o6aXLflqw=,tag:FXuvmsHqgBV+q6rfWI2JMw==,type:str]
NEXT_PUBLIC_APP_NAME: ENC[AES256_GCM,data:ApXOv0BHKL9eCVG2Vt7vcU3a+2Qs,iv:Tq6QTXbzsuJ/ZrODBo08kAlaIMtWBAoBWcSM9CEfp90=,tag:NVT8GZzdwZLebAKneu/K0Q==,type:str]
DATABASE_URL: ENC[AES256_GCM,data:bofWIKua58IFvxgW6/JjPk61385u88sZiR/UV7fkOdgHiU4W+IExdDZrv5b4pNYSbLMbvwv/35G+5P5kW5pAQVMKe3azXA==,iv:eDWLZtHYD3KJzasdWMj5NkKmdCtRN9pyoGa5V2giTxw=,tag:e20kb6Uy2g/hvCGAxnI3dg==,type:str]
POSTGRES_USER: ENC[AES256_GCM,data:1yIzv0grOAk=,iv:m1L+8yNpWpQiM0q9n6RY3pHw6QXd+31EXdbDvVhK6Hg=,tag:Mcv6UIqxmNU89IoDPjemzw==,type:str]
POSTGRES_PASSWORD: ENC[AES256_GCM,data:5oc2G94bJJP8FA==,iv:PQJecoEKZ14NhjFgWwmMvEBEC3xWdcdYcVGOyN90Pcc=,tag:iq7ik54EXUyonqpvJAGFEw==,type:str]
POSTGRES_DB: ENC[AES256_GCM,data:zbFaLLTWEirJnZtK4/QjBfUtDWdl,iv:3wcxGsGGmsGMdkSuqlxa8nVAnkHZgj52SBmh+5VrSu0=,tag:+GIj6pEBztIYvLhE4eoU7A==,type:str]
AUTH_SESSION_SECRET: ENC[AES256_GCM,data:Z3uOiBQXvT4DGVj0mOKL42RQax6qAgpi3B/P+6TxN0aM24Aa3g9tdIUUZmvhxOIP3MsnDJvIapQr+KwYWkUPyA==,iv:vWB8Z/pUXDXDiEEMJ2ks9hthf8yix0Kh5lwQA68rbK8=,tag:4uEnACl3WydEwt82IbG4XA==,type:str]
MAX_CHARTS_PER_USER: ENC[AES256_GCM,data:eg==,iv:AVdAynRBtGkYhINiRL6szvhleSqWf8dmNaFRdXnxT7g=,tag:EAKw14Xksh6cnA7ininRZA==,type:str]
KUNDLI_ENGINE_BACKEND: ENC[AES256_GCM,data:tTxBXJs6uKyQ,iv:MnRim1UgbJVLZ+2/MCdI98c+XqNZ+ibJ9oJO8yfjzDs=,tag:uSWnHm5mE9A3iznwlOm6Qg==,type:str]
KUNDLI_SPICE_KERNEL_DIR: ENC[AES256_GCM,data:yG6mwWviptzLU/6cIMu2B6qFut0ObGBPiemggg0h0y2AKYin,iv:QeZe9KNKygmvuj8G6aTVI5a1bap1k6iGBzIn+te21mQ=,tag:Oal5z8gfePimAOJx621pYw==,type:str]
POSTGRES_PORT: ENC[AES256_GCM,data:Hl+v6A==,iv:ItVBU6jp+1Ej8+oT3uYVOPGNA/bpKs9B5MHbL0BbiGI=,tag:ucirp6aIyleVwNTTyqM8tA==,type:str]
sops:
    age:
        - recipient: age1rg39ms6c7v27wgrnszy5zdysk3ntk63g2amhlg8als738zechpmqz5vcm3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsb0lmbmMxZUtRdUNPSnQ0
            bEVKQjkwcmpSNExleFJVdUgwbFhtWS8vb0RRCmNScCtralphNE50azMxSE0xdzVm
            L3p4bzFHL0ovelhPemZXSWY1dFlCNTgKLS0tIFN0YjdudWkxdmVSM1dMWVVuZkI2
            K1hvQXlMeUxPNVlab3gwZ0llQzBTSmMKzbXEC7rpgfIhF2B+Uugly2bEpn/K46bG
            YssqRHrFmbfgi+JPQB171eYwSvWPkJeS7r8bE9Iy4KiO1anKA+a7Qg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-12T19:40:35Z"
    mac: ENC[AES256_GCM,data:zL7lXTasJA4WuaOgqRxFL4gcArmWb0SVu1GvL1O45NS/rTvG09+E9M6BQLXfSHICXhdrVtjVEH1e81tacUIKvLjXL+qjILZz489QNDuEfjRJHWSBeK3fqrZISR84PsuAYhR93bkD+CeTqGRSjOve26tz9yzE1pbrt2XlymGyhkY=,iv:gz6rSvmsrp3Bar1+6WUqreg9xaXjMH0hfhe9EyaM8OY=,tag:PdpM7x/GIOoElAxdYqjSMA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
